### ISSUE TITLE
Support for multiple channels

### ISSUE THREAD

**Issue by FC5570** [daydreamercodes/youtube-notifier#1]
Does this support multiple YouTube channels?

**Comment by daydreamercodes** [comment]
Unfortunately no, it doesn't. You can use [youtube-notification](https://www.npmjs.com/package/youtube-notification)

**Comment by FC5570** [comment]
I need help with setting up youtube-notification, I've done everything as said in the readme, but the package doesn't work, like I've made it console log a line of text when it subscribes to a channel, it doesn't do that. Here's how I'm doing it:

```
const YouTubeNotifier = require('youtube-notification');

const notifier = new YouTubeNotifier({
  hubCallback: 'http://ip:port',
  port: poert,
  secret: 'Something',
  path: '/youtube'
});
notifier.setup()

notifier.on('notified', data => {
  console.log('New Video');
  console.log(
    `${data.channel.name} just uploaded a new video titled: ${data.video.title}`
  );
});
notifier.subscribe('my channel url');

notifier.on('subscribe', () => {
console.log('subscribed')
})
```
Please help

**Comment by daydreamercodes** [comment]
I'm not the owner or a contributor of that module. Sorry, I can't help.

**Comment by FC5570** [comment]
Can you please link me the github repo of the YouTube channel? The link on the npm package is wrong

**Comment by daydreamercodes** [comment]
Oh, it doesn't have a repo or they made it private. You can ask youtube-notification's collaborators. You can find them in youtube-notification's npmjs.com page. Good luck!

**Comment by FC5570** [comment]
The package (youtube-notification) is basically dead, their GitHub doesn't exist, I know one of the collaborators (CTK), but he doesn't seem to know how to fix this either. I've come across another package like this: [youtube-watch](https://www.npmjs.com/package/youtube-watch) I'v tried using it and even it doesn't work, idk what to do at this point, are you planning to add mutli channel support? Please do...

**Comment by daydreamercodes** [comment]
youtube-notifier is using puppeteer to scrape video data. So it may cause some problems. I can't say anything about multiple channel support right now. Feel free to edit the code if you wanna add it yourself, have a nice day!

**Comment by FC5570** [comment]
i guess you can close this now, ive figured out how to work with pubsubhubbub and it works. thanks for your help

**Comment by daydreamercodes** [comment]
Great! I'm going to add multi channel support to youtube-notifier soon. That's why I've pinned this issue.

**Comment by daydreamercodes** [comment]
youtube-notifier supports multiple channels now!
