### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Jake0303** [daydreamercodes/youtube-notifier#4]
Just installed this package on npm, it works but on first run for my NodeJS application I get this error :

**TypeError: Cannot read property 'id' of undefined
    at C:\Users\Jake0\WeTradeHQ\node_modules\youtube-notifier\index.js:26:51
    at processTicksAndRejections (internal/process/task_queues.js:97:5)**

**Comment by daydreamercodes** [comment]
Just released an update. Can you check if the issue is fixed?

**Comment by Jake0303** [comment]
> Just released an update. Can you check if the issue is fixed?

Yup, all good now!
